#! /bin/sh
case "$1" in
	start)
		echo "Starting aesd_client"
		start-stop-daemon -S -n aesd_client -a /usr/bin/aesdsocket -- -d
		;;
	stop)
		echo "Stopping aesd_client"
		start-stop-daemon -K -n aesd_client
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
